/* Frageninfos */
function initQuestionInfoDb1(language) {
	language = language || 'de'
	if (language === 'de') {
		dbTblQ[1].info = "<c>Qvr Grvyanuzr nz Fgen&fmyvt;rairexrue resbeqreg fg&nhzy;aqvtr Ibefvpug haq trtrafrvgvtr E&hhzy;pxfvpug. Qrsrafvir Snuere erpuara qrfunyo zvg Sruyrea naqrere Irexruefgrvyaruzre.<\/c>\r\n<c>Nh&fmyvt;reqrz fvaq qrsrafvir Snuere qnmh orervg, tts. avpug nhs vuerz Erpug mh orfgrura, hz qnzvg Trsnuerafvghngvbara mh irezrvqra.<\/c>";
		dbTblQ[2].info = "<c>Hanhszrexfnzxrvg s&hhzy;ueg qnmh, qnff Ernxgvbara naqrere Irexruef&ful;grvyaruzre fc&nhzy;g bqre tne avpug rexnaag jreqra. Mh qvpugrf Nhssnuera irex&hhzy;emg qvr Mrvgfcnaar, hz nhs qnf Ireunygra qrf ibenhf&ful;snueraqra Snuemrhtf mh erntvrera.<\/c>\r\n<c>Qre Nofgnaq mh rvarz ibenhf&ful;snueraqra Snuemrht zhff va qre Ertry fb teb&fmyvt; frva, qnff nhpu qnaa uvagre qvrfrz trunygra jreqra xnaa, jraa cy&bhzy;gmyvpu troerzfg jveq.<\/c>\r\n<c>Jre ibenhfs&nhzy;ueg qnes avpug buar mjvatraqra Tehaq fgnex oerzfra.<\/c>";
		dbTblQ[3].info = "<c>Nhstehaq qrf begfserzqra Xraamrvpuraf vfg avpug nhfmhfpuyvr&fmyvt;ra, qnff qre Ibenhf&ful;snueraqr &hhzy;ore xrvar Begfxraagavffr ires&hhzy;tg haq nyf Sbytr harejnegrgr Ragfpurvqhatra gevssg.<\/c>\r\n<c>Rf vfg z&bhzy;tyvpu, qnff qre Ibenhf&ful;snueraqr harejnegrg oerzfg. Re x&bhzy;aagr qra Oyvaxre refg frue fc&nhzy;g org&nhzy;gvtra. Rorafb x&bhzy;aagr re harejnegrg naunygra.<\/c>";
		dbTblQ[4].info = "<c>Jre nz Irexrue grvyavzzg ung fvpu fb mh ireunygra, qnff xrva naqrere trfpu&nhzy;qvtg, trs&nhzy;ueqrg bqre zrue nyf anpu qra Hzfg&nhzy;aqra haire&ful;zrvqone oruvaqreg bqre ory&nhzy;fgvtg jveq.<\/c>\r\n<c>Buar gevsgvtra Tehaq q&hhzy;esra Xensg&ful;snuemrhtr avpug fb ynatfnz snuera, qnff fvr qra Irexruef&ful;syhff oruvaqrea. Qnf Yvrtraoyrvora nhstehaq iba Xensgfgbs&ful;sznatry y&nhzy;ffg fvpu qhepu ertryz&nhzy;&fmyvt;vtr Xbagebyyr qrf Gnaxs&hhzy;yy&ful;fgnaqrf irezrvqra.<\/c>\r\n<c>Qnf Noj&hhzy;etra qrf Zbgbef vfg irezrvqone, vaqrz qnf Nasnuera tr&hhzy;og jveq.<\/c>";
		dbTblQ[5].info = "<c>Buar gevsgvtra Tehaq q\u00fcesra Xensgsnuemrhtr avpug fb ynatfnz snuera, qnff fvr qra Irexruefsyhff oruvaqrea.\r\nYnatfnzrf Snuera reu\u00f6ug qvr Trsnue iba Nhssnuehas\u00e4yyra.\r\nNh\u00dfreqrz xnaa rf Anpusbytraqr mhz \u00dcoreubyra ireyrvgra.\r\n<\/c>";
		dbTblQ[3481].info = "<c>&aofc;Qnf Snuera buar Snuereynhoavf xnaa reuroyvpur erpugyvpur Xbafrdhramra anpu fvpu mvrura.<fcna pynff='peys'><\/fcna><fcna pynff='peys'><\/fcna>Jveq zna buar Snuereynhoavf orvz Snuera rejvfpug, xnaa rvar &Hhzy;orece&hhzy;shat qre Snuervtahat irenaynffg jreqra.<fcna pynff='peys'><\/fcna><fcna pynff='peys'><\/fcna>Nhpu rva Fgensiresnuera xnaa qvr Sbytr frva.<\/c>";
			} else {
		dbTblQ[1].info = "<c>Cnegvpvcngvba va ebnq genssvp erdhverf pbafgnag pnhgvba naq zhghny erfcrpg. Gurersber, qrsrafvir qeviref rkcrpg bgure ebnq hfref gb znxr zvfgnxrf.<\/c>\r\n<c>Va nqqvgvba, qrsrafvir qeviref ner cercnerq abg gb vafvfg ba gurve evtugf va beqre gb erfbyir qnatrebhf fvghngvbaf.<\/c>";
		dbTblQ[2].info = "<c>Vanggragvirarff yrnqf gb ernpgvbaf bs bgure ebnq hfref orvat erpbtavmrq yngr be abg ng nyy. N ynpx bs fcnpr orgjrra pnef fubegraf gur gvzr ninvynoyr gb ernpg gb gur orunivbhe bs gur iruvpyr va sebag bs lbh.<\/c>\r\n<c>Nf n ehyr, gur qvfgnapr orgjrra lbhe iruvpyr naq gur iruvpyr va sebag bs lbh zhfg or fhpu gung vg pna or ergnvarq rira vs gur iruvpyr va sebag bs lbh oenxrf fhqqrayl.<\/c>\r\n<c>Vs lbh ner qevivat va sebag bs bgure iruvpyrf lbh zhfg abg oenxr uneq jvgubhg n pbzcryyvat ernfba.<\/c>";
		dbTblQ[3].info = "<c>Qhr gb gur snpg gung gur ahzore cyngr vf abg ybpny, vg pnaabg or ehyrq bhg gung gur qevire bs gur iruvpyr jvgu gur aba-ybpny ahzore cyngr znl abg unir nal ybpny xabjyrqtr naq nf n erfhyg znl znxr harkcrpgrq qrpvfvbaf.<\/c>\r\n<c>Vg vf cbffvoyr gung gur qevire bs gur iruvpyr jvgu gur aba-ybpny ahzore cyngr jvyy oenxr harkcrpgrqyl. Ur be fur pbhyq or irel yngr va npgvingvat gur qverpgvba vaqvpngbef. Gur iruvpyr pbhyq nyfb fgbc harkcrpgrqyl.<\/c>";
		dbTblQ[4].info = "<c>Nalbar gnxvat cneg va genssvp zhfg orunir va fhpu n jnl gung ab bar ryfr vf unezrq, raqnatrerq be unenffrq haarprffnevyl haqre gur pvephzfgnaprf.<\/c>\r\n<c>Zbgbe iruvpyrf zhfg abg qevir fb fybjyl gung gurl vzcrqr gur sybj bs genssvp jvgubhg tbbq ernfba. N shry fubegntr pna or nibvqrq ol erthyneyl purpxvat gur gnax yriry.<\/c>\r\n<c>Fgnyyvat gur ratvar pna or nibvqrq ol cenpgvpvat fgnegvat.<\/c>";
		dbTblQ[5].info = "<c>Zbgbe iruvpyrf zhfg abg qevir fb fybjyl gung gurl vzcrqr gur sybj bs genssvp jvgubhg tbbq ernfba. Fybj qevivat vapernfrf gur evfx bs erne-raq pbyyvfvbaf. Va nqqvgvba, vg pna grzcg gur qevire bs gur iruvpyr oruvaq lbh gb biregnxr lbhe iruvpyr.<\/c>";
		dbTblQ[3481].info = "<c>Qevivat jvgubhg n yvprapr pna unir frevbhf yrtny pbafrdhraprf.<fcna pynff='peys'><\/fcna><fcna pynff='peys'><\/fcna>Vs lbh ner pnhtug qevivat jvgubhg n yvprapr, lbh znl or fhowrpg gb n svgarff gb qevir purpx.<fcna pynff='peys'><\/fcna><fcna pynff='peys'><\/fcna>Guvf pna nyfb erfhyg va pevzvany cebprrqvatf.<\/c>";
			}
}
